### ISSUE TITLE
Unable to add SDK

### ISSUE THREAD

**Issue by Thexder** [4ch1m/kick-assembler-acbg#10]
Using Intellij Community-Edition 2020.3 and downloaded the plugin 1.4 from marketplace.
Already using Kickassembler v5.16 with another IDE and runs fine (manually configured path and parameters)

Problem: I'm failing in properly adding the kick ass folder as SDK. I'm using the described way of adding the kickass SDK via Project Settings. The kickass folder contains the KickAss.jar in the root.

On the console I get the following error message:
```
2020-12-22 16:28:36,901 [  23333]   WARN - s.ui.configuration.SdkDetector - No version is returned for detected SDK IDEA JDK at C:/ti8m/tools/ideaIC-2020.3
2020-12-22 16:28:46,379 [  32811]  ERROR - pplication.impl.LaterInvocator - Argument for @NotNull parameter 'suggestedName' of com/intellij/openapi/projectRoots/impl/SdkConfigurationUtil.createUniqueSdkName must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'suggestedName' of com/intellij/openapi/projectRoots/impl/SdkConfigurationUtil.createUniqueSdkName must not be null
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.$$$reportNull$$$0(SdkConfigurationUtil.java)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.createUniqueSdkName(SdkConfigurationUtil.java)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.createUniqueSdkName(SdkConfigurationUtil.java:268)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.createSdk(ProjectSdksModel.java:453)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.addSdk(ProjectSdksModel.java:447)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$2.lambda$actionPerformed$1(ProjectSdksModel.java:412)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.lambda$selectSdkHome$7(SdkConfigurationUtil.java:304)
        at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:146)
        at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:101)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:301)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:279)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$2.actionPerformed(ProjectSdksModel.java:412)
        at com.intellij.openapi.roots.ui.configuration.SdkListModelBuilder.executeAction(SdkListModelBuilder.java:268)
        at com.intellij.openapi.roots.ui.configuration.JdkComboBox.setSelectedItem(JdkComboBox.java:287)
        at com.intellij.ide.ui.laf.darcula.ui.DarculaJBPopupComboPopup.lambda$createPopup$0(DarculaJBPopupComboPopup.java:275)
        at com.intellij.ui.popup.list.ComboBoxPopup$MyBasePopupState.lambda$onChosen$1(ComboBoxPopup.java:201)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:762)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)
        at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:46)
        at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:36)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
        at java.desktop/java.awt.Component.processEvent(Component.java:6417)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-12-22 16:28:46,386 [  32818]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.3  Build #IC-203.5981.155
2020-12-22 16:28:46,387 [  32819]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2020-12-22 16:28:46,388 [  32820]  ERROR - pplication.impl.LaterInvocator - OS: Windows 10
2020-12-22 16:28:46,389 [  32821]  ERROR - pplication.impl.LaterInvocator - Last Action: ShowProjectStructureSettings
```

**Comment by 4ch1m** [comment]
Do you have a Java SDK installed/set up?
Seems that IntelliJ has trouble with your setup:
> 2020-12-22 16:28:36,901 [  23333]   WARN - s.ui.configuration.SdkDetector - No version is returned for detected SDK IDEA JDK at C:/ti8m/tools/ideaIC-2020.3

A properly installed JavaSDK is needed to determine the KickAssemblerSDK version.

**Comment by Thexder** [comment]
Yeah, you're right. It said <null>... sorry. Now it works. Any plans for enhancing it? I mean the syntax coloring is having some minor issues, no suggestions (not labels, not macros, not commands....)
